name: Deploy Next.js with Docker to GCP

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jmf-web:latest
          build-args: |
            NEXT_PUBLIC_SERVER=${{ secrets.NEXT_PUBLIC_SERVER }}
            NEXT_PUBLIC_LOCAL_SERVER=${{ secrets.NEXT_PUBLIC_LOCAL_SERVER }}

      - name: Deploy to GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST_SERVER }}
          username: ${{ secrets.GCP_HOST_NAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/jmf-web:latest
            docker stop jmf-web || true
            docker rm jmf-web || true
            docker run -d --name jmf-web \
              -e TZ=Asia/Seoul \
              -p 3000:3000 \
              ${{ secrets.DOCKER_USERNAME }}/jmf-web:latest
